version: "3.7"

services:
  nuxt-app:
    build: ./Cambodia-Food-Review
    container_name: nuxt-app
    restart: always
    ports:
      - "3001:3001"
    command: "npm run start"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
 
